# Generated by Django 2.1.5 on 2019-01-11 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img',
            field=models.ImageField(max_length=200, null=True, upload_to='users/', verbose_name='用户头像'),
        ),
    ]
