# Generated by Django 2.1.5 on 2019-01-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='desc',
            field=models.TextField(default=None, null=True, verbose_name='用户简介'),
        ),
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.ImageField(default=None, max_length=200, null=True, upload_to='users/', verbose_name='用户头像'),
        ),
    ]
