# Generated by Django 2.1.5 on 2019-01-10 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True, verbose_name='文章标题')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('keyword', models.CharField(max_length=30, verbose_name='关键字')),
                ('describe', models.CharField(max_length=100, verbose_name='文章描述')),
                ('title_img', models.ImageField(max_length=200, upload_to='article/', verbose_name='文章封面')),
                ('state', models.CharField(choices=[('publish', '公布'), ('private', '私密')], max_length=10, verbose_name='发布状态')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='Columns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('alias', models.CharField(max_length=20, null=True)),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('columns', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coll', to='myblog.Columns')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200, verbose_name='评论内容')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='com', to='myblog.Article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='com', to='users.User')),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='标签名称')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('article', models.ManyToManyField(related_name='lab', to='myblog.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Ly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u', to='users.User')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='col',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='col', to='myblog.Columns'),
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='users.User'),
        ),
    ]
