# Generated by Django 2.1.5 on 2019-01-10 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='columns',
            name='desc',
            field=models.CharField(max_length=200, null=True, verbose_name='栏目描述'),
        ),
        migrations.AddField(
            model_name='columns',
            name='keyword',
            field=models.CharField(max_length=50, null=True, verbose_name='栏目关键字'),
        ),
        migrations.AlterField(
            model_name='article',
            name='col',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='col', to='myblog.Columns', verbose_name='所属栏目'),
        ),
        migrations.AlterField(
            model_name='article',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='users.User', verbose_name='所属作者'),
        ),
        migrations.AlterField(
            model_name='columns',
            name='alias',
            field=models.CharField(max_length=20, null=True, verbose_name='栏目别名'),
        ),
        migrations.AlterField(
            model_name='columns',
            name='columns',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coll', to='myblog.Columns', verbose_name='栏目父节点'),
        ),
        migrations.AlterField(
            model_name='columns',
            name='name',
            field=models.CharField(max_length=10, unique=True, verbose_name='栏目名称'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='com', to='myblog.Article', verbose_name='评论的文章'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='com', to='users.User', verbose_name='所属人'),
        ),
        migrations.AlterField(
            model_name='label',
            name='article',
            field=models.ManyToManyField(related_name='lab', to='myblog.Article', verbose_name='多对多文章'),
        ),
        migrations.AlterField(
            model_name='ly',
            name='content',
            field=models.CharField(max_length=200, verbose_name='留言内容'),
        ),
        migrations.AlterField(
            model_name='ly',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u', to='users.User', verbose_name='留言人'),
        ),
    ]
