# Generated by Django 2.1.5 on 2019-01-10 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_auto_20190110_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columns',
            name='columns',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coll', to='myblog.Columns', verbose_name='栏目父节点'),
        ),
    ]
