# Generated by Django 2.1.5 on 2019-01-14 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190114_2000'),
        ('myblog', '0004_auto_20190110_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ly',
            name='user',
        ),
        migrations.AddField(
            model_name='ly',
            name='fromUser',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='fromu', to='users.User', verbose_name='留言人'),
        ),
        migrations.AddField(
            model_name='ly',
            name='toUser',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tou', to='users.User', verbose_name='接收留言人'),
        ),
        migrations.AlterField(
            model_name='ly',
            name='content',
            field=models.CharField(default=None, max_length=200, null=True, verbose_name='留言内容'),
        ),
    ]
